name: Continuous Integration/Continuous Deployment

# Con esta configuración se ejecuta en cada push a cualquier rama
# on: [push]

on:
  push:
    branches:
      - main

jobs:
  # Nombre del proceso a ejecutar
  continuous-integration:
    # El proceso va a ejecutarse en una instancia de ubuntu
    runs-on: ubuntu-latest
    # Pasos a ejecutar
    steps:
        # Clonar el código
      - name: Clonar la última versión del código
        uses: actions/checkout@v4

        # Configurar el ambiente de Node.js
      - name: Ejecutar las pruebas en un ambiente de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
        
        # Corre los comandos de Node.js para asegurar la integridad del código
      - run: npm install
        # Agregando comando para pruebas
      #- run: npm test
    
  continuous-delivery:
    needs: continuous-integration
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USERNAME }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /var/www/xmed-project/
            git pull origin main
            npm install --production
            pm2 restart src/index.js
